'use strict';function j(g){throw g;}var k=null;
this.Blessed=function(){function g(a){return"function"===typeof a&&a.prototype!=k?a.prototype:a}function b(a,c,e){a==k&&j(Error(h(i.undefined,"unBindAt","object")));c==k&&j(Error(h(i.undefined,"unBindAt","func")));"string"===typeof c&&"function"===typeof a[c]&&(c=a[c]);"function"!==typeof c&&j(Error(h(i.notFunc,"unBindAt","func",c,typeof c)));e==k&&(e=0);e===m&&(e=(c._applyLength||c.length)-1);isNaN(e)&&j(Error(h(i.notNumber,"unBindAt","thisArgNumber",e,typeof e)));0>e&&j(Error(h(i.negative,"unBindAt",
"thisArgNumber",e)));return function(){var b=Array.prototype.slice.call(arguments,void 0);b.splice(e,0,this);return c.apply(a,b)}}function h(a){if(a==k)return k;for(var c=1,e=arguments.length;c<e;++c)a=a.replace("{"+(c-1)+"}",(arguments[c]||"").toString());return a}var i={undefined:"{0}: Bad argument: parameter '{1}' was null or undefined.",notFunc:"{0}: Bad argument: parameter '{1}' should be a function or the name of a function. Was '{2}' (type {3}).",notNumber:"{0}: Bad argument: parameter '{1}' should be a number. Was '{2}' (type {3}).",
negative:"{0}: Bad argument: parameter '{1}' may not be negative, was '{2}'.",unimplemented:"Interface property '{0}' is not implemented.",extendedProp:"{0}: Already extended: prototype has property '{1}' (type {2}).",alreadyExtended:"extend: Already extended."},m={toString:function(){return"LAST_ARG"}};return{interpolate:h,ERROR_MESSAGES:i,LAST_ARG:m,unBindAt:b,bless:function(a,c,e){c==k&&j(Error(h(i.undefined,"bless","benediction")));a==k&&j(Error(h(i.undefined,"bless","blessee")));var a=g(a),c=
g(c),l;for(l in c)a[l]==k&&(a[l]="function"===typeof c[l]?b(c,l,e):c[l])},extend:function(a,c){function e(){}a==k&&j(Error(h(i.undefined,"extend","subclass")));c==k&&j(Error(h(i.undefined,"extend","superclass")));if(a.prototype&&a.prototype.constructor===a)for(var b in a.prototype)!0===a.prototype.hasOwnProperty(b)&&j(Error(h(i.extendedProp,"extend",b,typeof a.prototype[b])));else j(Error(i.alreadyExtended));a.parent=c;e.prototype=c.prototype;a.prototype=new e},mixin:function(a,c){var b,l,f,d;a==
k&&j(Error(h(i.undefined,"mixin","child")));a=g(a);b=1;for(l=arguments.length;b<l;++b)for(f in d=g(arguments[b]),d)!1===a.hasOwnProperty(f)&&(a[f]=d[f]);return a},assertImplements:function(a,c){a==k&&j(Error(h(i.undefined,"assertImplements","child")));c==k&&j(Error(h(i.undefined,"assertImplements","interf")));var c=g(c),b;for(b in c)a[b]==k&&j(Error(h(i.unimplemented,b)))}}}();this.Functional=function(){function g(f,a){return Array.prototype.slice.call(f,a)}function b(f,a){function b(c){var e=function n(){if(0===arguments.length)return n;var e=g(arguments),e=c.concat(e);return e.length>=a?f.apply(this,e):b(e)};e._curried=!0;e._applyLength=a-c.length;return e}f==k&&j(Error("curry: Bad argument: Parameter 'func' was null or undefined."));void 0==a&&(a=f._applyLength||f.length);return 2>a||f._curried?f:b([])}function h(f){return b(function(){return g(arguments).reduce(f)},
f.length)}function i(f,a){return[a.apply(this,f)]}function m(f){return b(function(a,b){var c=g(arguments);c[0]=b;c[1]=a;return f.apply(this,c)},Math.max(2,f.a||f.length))}var a={or:function(a,d){return a||d},and:function(a,d){return a&&d},mod:function(a,d){return a%d},plus:function(a,d){return a+d},from:function(a,d){return a-d},take:function(a,d){return d-a},times:function(a,d){return a*d},divide:function(a,d){return a/d},by:function(a,d){return d/a},less:function(a,d){return a<d},greater:function(a,
d){return a>d},lessOrEqual:function(a,d){return a<=d},greaterOrEqual:function(a,d){return a>=d},equal:function(a,d){return a==d},same:function(a,d){return a===d},type:function(a){return typeof a},get:function(a,d){return d[a]},set:function(a,d,b){return b[a]=d},apply:function(a,d,b){return a.apply(b,d)},call:function(a){var d=g(arguments,1);return a.apply(this,d)},instance:function(a,d){return d instanceof a}};a.greaterThan=a.less;a.lessThan=a.greater;a.greaterThanOrEqual=a.lessOrEqual;a.lessThanOrEqual=
a.greaterOrEqual;var c=b(function(a,d){function b(){return c.reduceRight(i,g(arguments))[0]}var c=g(arguments);b._applyLength=c[c.length-1].length;return b}),e=b(function(a,d){var b=g(arguments);return function(){var a=g(arguments);return b.every(applyArgsToFunc(a))}}),l=b(function(a,d){var b=g(arguments);return function(){var a=g(arguments);return b.some(applyArgsToFunc(a))}});return{basic:a,plus:h(a.plus),minus:h(a.from),times:h(a.times),divide:b(a.by),less:b(a.lessThan),equal:b(a.equal),mod:b(a.mod),
lessOrEqual:b(a.lessThanOrEqual),greater:b(a.greaterThan),greaterOrEqual:b(a.greaterThanOrEqual),b:b(a.same),and:e,or:l,divisibleBy:function(a){return b(function(b){return 0==b%a})},compose:c,pipe:function(a,b){function c(){return e.reduce(i,g(arguments))[0]}var e=g(arguments);c._applyLength=a.a||a.length;return c},flip:m,apply:b(a.apply),ylppa:m(a.apply),call:b(a.call),curry:b,get:b(a.get),curryAll:function(a){for(var c in a)"function"==typeof a[c]&&(a[c]=b(a[c]))}}}();
